export const theme = {
  colors: {
    headColor: '#0F52BA',
    bgColor: '#FFFFFF',
    containerProduct: 'rgba(255, 255, 255, 0.1352)',
  },
  fonts: {
    name: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '19px',
      textAlign: 'left',
    },
    description: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '10px',
      fontWeight: 300,
      lineHeight: '12px',
      textAlign: 'left',
    },
    price: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '15px',
      fontWeight: 700,
      lineHeight: '15px',
      textAlign: 'left',
    },
    buy: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: '18px',
      textAlign: 'left',
    },
    pageTitle: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '40px',
      fontWeight: 600,
      lineHeight: '19px',
      textAlign: 'left',
    },
    pageSubTitle: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '20px',
      fontWeight: 300,
      lineHeight: '19px',
      textAlign: 'left',
      color: '#FFFFFF',
    },
    sideTitle: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '27px',
      fontWeight: 700,
      lineHeight: '32.91px',
      textAlign: 'left',
    },
    sideTOTAL: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '28px',
      fontWeight: 700,
      lineHeight: '15px',
      textAlign: 'left',
    },
    sideProdTitle: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '13px',
      fontWeight: 400,
      lineHeight: '17px',
      textAlign: 'left',
    },
    sideQtt: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '5px',
      fontWeight: 400,
      lineHeight: '6.1px',
      textAlign: 'left',
    },
    sideTopPrice: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '14px',
      fontWeight: 700,
      lineHeight: '17px',
      textAlign: 'left',
      color: '#000000',
    },
    sideBottonPrice: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '28px',
      fontWeight: 700,
      lineHeight: '15px',
      textAlign: 'left',
    },
    finalBuy: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '28px',
      fontWeight: 700,
      lineHeight: '15px',
      textAlign: 'left',
    },
    footTitle: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: '12px',
      fontWeight: 400,
      lineHeight: '14.63px',
      textAlign: 'left',
      color: '#000000',
    },
  },
};
